# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/system_MIPI_CSI_2_RX_0_0.xci
# IP: The module: 'system_MIPI_CSI_2_RX_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/line_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==line_buffer || ORIG_REF_NAME==line_buffer} -quiet] -quiet

# IP: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/cdc_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cdc_fifo || ORIG_REF_NAME==cdc_fifo} -quiet] -quiet

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/line_buffer_ooc.xdc

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/line_buffer/line_buffer.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==line_buffer || ORIG_REF_NAME==line_buffer} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/cdc_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cdc_fifo || ORIG_REF_NAME==cdc_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/cdc_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cdc_fifo || ORIG_REF_NAME==cdc_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/mipi_csi2_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_MIPI_CSI_2_RX_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/mipi_csi2_rx_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_MIPI_CSI_2_RX_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/mipi_csi2_rx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_MIPI_CSI_2_RX_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/system_MIPI_CSI_2_RX_0_0.xci
# IP: The module: 'system_MIPI_CSI_2_RX_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/line_buffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==line_buffer || ORIG_REF_NAME==line_buffer} -quiet] -quiet

# IP: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/cdc_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cdc_fifo || ORIG_REF_NAME==cdc_fifo} -quiet] -quiet

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/line_buffer_ooc.xdc

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/line_buffer/line_buffer.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==line_buffer || ORIG_REF_NAME==line_buffer} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/cdc_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cdc_fifo || ORIG_REF_NAME==cdc_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/cdc_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cdc_fifo || ORIG_REF_NAME==cdc_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/mipi_csi2_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_MIPI_CSI_2_RX_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/mipi_csi2_rx_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_MIPI_CSI_2_RX_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Github/Zybo_Pcam/Zybo-Z7-20-pcam-5c-changeRGB/src/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/mipi_csi2_rx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_MIPI_CSI_2_RX_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
