# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/GitHub/Zybo_Pcam/project_1/project_1.srcs/sources_1/ip/v_frmbuf_rd_0/v_frmbuf_rd_0.xci
# IP: The module: 'v_frmbuf_rd_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/GitHub/Zybo_Pcam/project_1/project_1.srcs/sources_1/ip/v_frmbuf_rd_0/v_frmbuf_rd_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_frmbuf_rd_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: z:/GitHub/Zybo_Pcam/project_1/project_1.srcs/sources_1/ip/v_frmbuf_rd_0/v_frmbuf_rd_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_frmbuf_rd_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: z:/GitHub/Zybo_Pcam/project_1/project_1.srcs/sources_1/ip/v_frmbuf_rd_0/v_frmbuf_rd_0.xci
# IP: The module: 'v_frmbuf_rd_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/GitHub/Zybo_Pcam/project_1/project_1.srcs/sources_1/ip/v_frmbuf_rd_0/v_frmbuf_rd_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_frmbuf_rd_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: z:/GitHub/Zybo_Pcam/project_1/project_1.srcs/sources_1/ip/v_frmbuf_rd_0/v_frmbuf_rd_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_frmbuf_rd_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
