// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module v_frmbuf_rd_0_Bytes2MultiPixStream (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        bytes_plane0_V_V_dout,
        bytes_plane0_V_V_empty_n,
        bytes_plane0_V_V_read,
        img_V_val_0_V_din,
        img_V_val_0_V_full_n,
        img_V_val_0_V_write,
        img_V_val_1_V_din,
        img_V_val_1_V_full_n,
        img_V_val_1_V_write,
        img_V_val_2_V_din,
        img_V_val_2_V_full_n,
        img_V_val_2_V_write,
        img_V_val_3_V_din,
        img_V_val_3_V_full_n,
        img_V_val_3_V_write,
        img_V_val_4_V_din,
        img_V_val_4_V_full_n,
        img_V_val_4_V_write,
        img_V_val_5_V_din,
        img_V_val_5_V_full_n,
        img_V_val_5_V_write,
        Height,
        Width,
        mul_ln131_loc_dout,
        mul_ln131_loc_empty_n,
        mul_ln131_loc_read,
        HwReg_video_format
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_state11 = 28'd1024;
parameter    ap_ST_fsm_state12 = 28'd2048;
parameter    ap_ST_fsm_state13 = 28'd4096;
parameter    ap_ST_fsm_state14 = 28'd8192;
parameter    ap_ST_fsm_state15 = 28'd16384;
parameter    ap_ST_fsm_state16 = 28'd32768;
parameter    ap_ST_fsm_state17 = 28'd65536;
parameter    ap_ST_fsm_state18 = 28'd131072;
parameter    ap_ST_fsm_state19 = 28'd262144;
parameter    ap_ST_fsm_pp0_stage0 = 28'd524288;
parameter    ap_ST_fsm_pp0_stage1 = 28'd1048576;
parameter    ap_ST_fsm_pp0_stage2 = 28'd2097152;
parameter    ap_ST_fsm_pp0_stage3 = 28'd4194304;
parameter    ap_ST_fsm_pp0_stage4 = 28'd8388608;
parameter    ap_ST_fsm_pp0_stage5 = 28'd16777216;
parameter    ap_ST_fsm_pp0_stage6 = 28'd33554432;
parameter    ap_ST_fsm_pp0_stage7 = 28'd67108864;
parameter    ap_ST_fsm_state29 = 28'd134217728;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [127:0] bytes_plane0_V_V_dout;
input   bytes_plane0_V_V_empty_n;
output   bytes_plane0_V_V_read;
output  [7:0] img_V_val_0_V_din;
input   img_V_val_0_V_full_n;
output   img_V_val_0_V_write;
output  [7:0] img_V_val_1_V_din;
input   img_V_val_1_V_full_n;
output   img_V_val_1_V_write;
output  [7:0] img_V_val_2_V_din;
input   img_V_val_2_V_full_n;
output   img_V_val_2_V_write;
output  [7:0] img_V_val_3_V_din;
input   img_V_val_3_V_full_n;
output   img_V_val_3_V_write;
output  [7:0] img_V_val_4_V_din;
input   img_V_val_4_V_full_n;
output   img_V_val_4_V_write;
output  [7:0] img_V_val_5_V_din;
input   img_V_val_5_V_full_n;
output   img_V_val_5_V_write;
input  [15:0] Height;
input  [15:0] Width;
input  [15:0] mul_ln131_loc_dout;
input   mul_ln131_loc_empty_n;
output   mul_ln131_loc_read;
input  [15:0] HwReg_video_format;

reg ap_done;
reg ap_idle;
reg start_write;
reg bytes_plane0_V_V_read;
reg[7:0] img_V_val_0_V_din;
reg img_V_val_0_V_write;
reg[7:0] img_V_val_1_V_din;
reg img_V_val_1_V_write;
reg[7:0] img_V_val_2_V_din;
reg img_V_val_2_V_write;
reg[7:0] img_V_val_3_V_din;
reg img_V_val_3_V_write;
reg[7:0] img_V_val_4_V_din;
reg img_V_val_4_V_write;
reg[7:0] img_V_val_5_V_din;
reg img_V_val_5_V_write;
reg mul_ln131_loc_read;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    bytes_plane0_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] icmp_ln708_reg_1409;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
reg   [0:0] or_ln715_reg_1418;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
reg   [0:0] or_ln717_reg_1422;
reg    img_V_val_0_V_blk_n;
reg   [0:0] or_ln734_reg_1426;
reg   [0:0] or_ln734_1_reg_1430;
reg   [0:0] or_ln734_2_reg_1434;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
reg   [0:0] or_ln734_3_reg_1438;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
reg   [0:0] or_ln734_4_reg_1442;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
reg   [0:0] or_ln734_5_reg_1446;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7;
reg   [0:0] or_ln734_6_reg_1450;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] or_ln734_7_reg_1454;
reg    img_V_val_1_V_blk_n;
reg    img_V_val_2_V_blk_n;
reg    img_V_val_3_V_blk_n;
reg    img_V_val_4_V_blk_n;
reg    img_V_val_5_V_blk_n;
reg    mul_ln131_loc_blk_n;
reg   [10:0] x_0_i_i_reg_371;
reg    ap_block_state1;
wire   [0:0] icmp_ln418_fu_408_p2;
wire   [0:0] icmp_ln459_fu_430_p2;
wire   [0:0] icmp_ln514_fu_452_p2;
wire   [0:0] icmp_ln571_fu_474_p2;
wire   [0:0] icmp_ln614_fu_480_p2;
wire   [0:0] icmp_ln651_fu_486_p2;
wire   [0:0] icmp_ln688_fu_508_p2;
reg   [12:0] trunc_ln_reg_1316;
wire   [0:0] icmp_ln697_fu_538_p2;
wire   [2:0] lshr_ln_fu_544_p4;
wire   [12:0] add_ln693_fu_554_p2;
reg   [12:0] add_ln693_reg_1333;
wire    ap_CS_fsm_state2;
wire   [27:0] mul_ln693_fu_1265_p2;
reg   [27:0] mul_ln693_reg_1338;
wire    ap_CS_fsm_state3;
reg   [11:0] trunc_ln1_reg_1343;
wire    ap_CS_fsm_state4;
wire   [11:0] add_ln715_fu_590_p2;
reg   [11:0] add_ln715_reg_1349;
wire    ap_CS_fsm_state18;
wire   [0:0] icmp_ln715_fu_595_p2;
reg   [0:0] icmp_ln715_reg_1355;
wire   [0:0] icmp_ln717_fu_601_p2;
reg   [0:0] icmp_ln717_reg_1360;
wire   [0:0] icmp_ln734_fu_607_p2;
wire   [0:0] icmp_ln734_1_fu_623_p2;
wire   [0:0] icmp_ln734_2_fu_629_p2;
wire   [0:0] icmp_ln734_3_fu_645_p2;
wire   [0:0] icmp_ln734_4_fu_651_p2;
wire   [0:0] icmp_ln734_5_fu_657_p2;
wire   [0:0] icmp_ln734_6_fu_663_p2;
wire   [0:0] icmp_ln700_fu_669_p2;
wire    ap_CS_fsm_state19;
wire   [15:0] y_fu_674_p2;
reg   [15:0] y_reg_1404;
wire   [0:0] icmp_ln708_fu_684_p2;
wire    ap_block_state20_pp0_stage0_iter0;
wire    io_acc_block_signal_op237;
reg    ap_block_state28_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [10:0] x_fu_689_p2;
reg   [10:0] x_reg_1413;
wire   [0:0] or_ln715_fu_700_p2;
wire   [0:0] or_ln717_fu_710_p2;
wire   [0:0] or_ln734_fu_715_p2;
wire   [0:0] or_ln734_1_fu_720_p2;
wire   [0:0] or_ln734_2_fu_725_p2;
wire   [0:0] or_ln734_3_fu_730_p2;
wire   [0:0] or_ln734_4_fu_735_p2;
wire   [0:0] or_ln734_5_fu_740_p2;
wire   [0:0] or_ln734_6_fu_745_p2;
wire   [0:0] or_ln734_7_fu_750_p2;
reg   [7:0] tmp_val_0_V_1_reg_1458;
wire    io_acc_block_signal_op166;
reg    ap_predicate_op166_write_state21;
reg    ap_block_state21_pp0_stage1_iter0;
reg    ap_block_pp0_stage1_11001;
reg   [7:0] tmp_val_1_V_1_reg_1463;
reg   [7:0] tmp_val_2_V_1_reg_1468;
reg   [7:0] tmp_val_3_V_1_reg_1473;
reg   [7:0] tmp_val_4_V_1_reg_1478;
reg   [7:0] tmp_val_5_V_1_reg_1483;
reg   [7:0] tmp_val_0_V_2_reg_1488;
reg   [7:0] tmp_val_1_V_2_reg_1493;
reg   [7:0] tmp_val_2_V_2_reg_1498;
reg   [7:0] tmp_val_3_V_2_reg_1503;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state20;
wire    io_acc_block_signal_op228;
reg    ap_predicate_op228_write_state27;
reg    ap_block_state27_pp0_stage7_iter0;
reg    ap_block_pp0_stage7_subdone;
reg   [15:0] y_0_i_i_reg_360;
wire    ap_CS_fsm_state29;
reg   [10:0] ap_phi_mux_x_0_i_i_phi_fu_375_p4;
reg   [127:0] tmp_V_fu_300;
reg    ap_predicate_op185_read_state23;
wire    io_acc_block_signal_op191;
reg    ap_predicate_op191_write_state23;
reg    ap_block_state23_pp0_stage3_iter0;
reg    ap_block_pp0_stage3_11001;
reg   [127:0] tmp_V_1_fu_304;
reg    ap_predicate_op180_read_state22;
wire    io_acc_block_signal_op183;
reg    ap_predicate_op183_write_state22;
reg    ap_block_state22_pp0_stage2_iter0;
reg    ap_block_pp0_stage2_11001;
wire   [7:0] tmp_val_0_V_fu_755_p1;
reg    ap_block_pp0_stage1_01001;
reg    ap_block_pp0_stage2_01001;
reg    ap_block_pp0_stage3_01001;
wire    io_acc_block_signal_op200;
reg    ap_predicate_op200_write_state24;
reg    ap_block_state24_pp0_stage4_iter0;
reg    ap_block_pp0_stage4_01001;
wire    io_acc_block_signal_op209;
reg    ap_predicate_op209_write_state25;
reg    ap_block_state25_pp0_stage5_iter0;
reg    ap_block_pp0_stage5_01001;
wire    io_acc_block_signal_op219;
reg    ap_predicate_op219_write_state26;
reg    ap_block_state26_pp0_stage6_iter0;
reg    ap_block_pp0_stage6_01001;
reg    ap_block_pp0_stage7_01001;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] tmp_val_2_V_5_fu_1095_p1;
wire   [7:0] tmp_val_4_V_2_fu_925_p1;
reg    ap_block_pp0_stage4_11001;
reg    ap_block_pp0_stage5_11001;
reg    ap_block_pp0_stage6_11001;
reg    ap_block_pp0_stage7_11001;
wire   [7:0] trunc_ln133_fu_388_p1;
wire   [7:0] add_ln418_fu_392_p2;
wire   [6:0] tmp_fu_398_p4;
wire   [7:0] add_ln459_fu_414_p2;
wire   [6:0] tmp_1_fu_420_p4;
wire   [7:0] add_ln514_fu_436_p2;
wire   [6:0] tmp_2_fu_442_p4;
wire   [7:0] add_ln571_fu_458_p2;
wire   [6:0] tmp_3_fu_464_p4;
wire   [7:0] add_ln688_fu_492_p2;
wire   [6:0] tmp_4_fu_498_p4;
wire   [16:0] zext_ln692_fu_514_p1;
wire   [16:0] add_ln692_fu_518_p2;
wire   [3:0] remainPix_fu_534_p1;
wire   [2:0] grp_fu_559_p1;
wire   [1:0] grp_fu_559_p2;
wire   [3:0] zext_ln697_fu_580_p1;
wire   [1:0] trunc_ln694_fu_576_p1;
wire   [3:0] select_ln697_fu_583_p3;
wire   [2:0] tmp_5_fu_613_p4;
wire   [1:0] tmp_6_fu_635_p4;
wire   [11:0] zext_ln708_fu_680_p1;
wire   [0:0] icmp_ln715_1_fu_695_p2;
wire   [0:0] icmp_ln717_1_fu_705_p2;
wire   [14:0] mul_ln693_fu_1265_p0;
wire   [12:0] mul_ln693_fu_1265_p1;
reg    grp_fu_559_ap_start;
wire    grp_fu_559_ap_done;
reg   [27:0] ap_NS_fsm;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [27:0] mul_ln693_fu_1265_p10;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 28'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

v_frmbuf_rd_0_v_frmbuf_rd_urem_cud #(
    .ID( 1 ),
    .NUM_STAGE( 17 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
v_frmbuf_rd_urem_cud_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_559_ap_start),
    .done(grp_fu_559_ap_done),
    .din0(trunc_ln_reg_1316),
    .din1(grp_fu_559_p1),
    .ce(1'b1),
    .dout(grp_fu_559_p2)
);

v_frmbuf_rd_0_v_frmbuf_rd_mul_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 28 ))
v_frmbuf_rd_mul_mdEe_U15(
    .din0(mul_ln693_fu_1265_p0),
    .din1(mul_ln693_fu_1265_p1),
    .dout(mul_ln693_fu_1265_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state19) & ((icmp_ln418_fu_408_p2 == 1'd1) | ((icmp_ln459_fu_430_p2 == 1'd1) | ((icmp_ln514_fu_452_p2 == 1'd1) | ((icmp_ln571_fu_474_p2 == 1'd1) | ((icmp_ln614_fu_480_p2 == 1'd1) | ((icmp_ln651_fu_486_p2 == 1'd1) | ((icmp_ln688_fu_508_p2 == 1'd0) | (icmp_ln700_fu_669_p2 == 1'd1)))))))))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state20) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln700_fu_669_p2 == 1'd0) & (icmp_ln651_fu_486_p2 == 1'd0) & (icmp_ln614_fu_480_p2 == 1'd0) & (icmp_ln571_fu_474_p2 == 1'd0) & (icmp_ln514_fu_452_p2 == 1'd0) & (icmp_ln459_fu_430_p2 == 1'd0) & (icmp_ln418_fu_408_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln688_fu_508_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((icmp_ln700_fu_669_p2 == 1'd0) & (icmp_ln651_fu_486_p2 == 1'd0) & (icmp_ln614_fu_480_p2 == 1'd0) & (icmp_ln571_fu_474_p2 == 1'd0) & (icmp_ln514_fu_452_p2 == 1'd0) & (icmp_ln459_fu_430_p2 == 1'd0) & (icmp_ln418_fu_408_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln688_fu_508_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln708_reg_1409 == 1'd1))) begin
        x_0_i_i_reg_371 <= x_reg_1413;
    end else if (((icmp_ln700_fu_669_p2 == 1'd0) & (icmp_ln651_fu_486_p2 == 1'd0) & (icmp_ln614_fu_480_p2 == 1'd0) & (icmp_ln571_fu_474_p2 == 1'd0) & (icmp_ln514_fu_452_p2 == 1'd0) & (icmp_ln459_fu_430_p2 == 1'd0) & (icmp_ln418_fu_408_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln688_fu_508_p2 == 1'd1))) begin
        x_0_i_i_reg_371 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        y_0_i_i_reg_360 <= y_reg_1404;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        y_0_i_i_reg_360 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln693_reg_1333 <= add_ln693_fu_554_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        add_ln715_reg_1349 <= add_ln715_fu_590_p2;
        icmp_ln715_reg_1355 <= icmp_ln715_fu_595_p2;
        icmp_ln717_reg_1360 <= icmp_ln717_fu_601_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln708_reg_1409 <= icmp_ln708_fu_684_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln693_reg_1338 <= mul_ln693_fu_1265_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln708_fu_684_p2 == 1'd1))) begin
        or_ln715_reg_1418 <= or_ln715_fu_700_p2;
        or_ln717_reg_1422 <= or_ln717_fu_710_p2;
        or_ln734_1_reg_1430 <= or_ln734_1_fu_720_p2;
        or_ln734_2_reg_1434 <= or_ln734_2_fu_725_p2;
        or_ln734_3_reg_1438 <= or_ln734_3_fu_730_p2;
        or_ln734_4_reg_1442 <= or_ln734_4_fu_735_p2;
        or_ln734_5_reg_1446 <= or_ln734_5_fu_740_p2;
        or_ln734_6_reg_1450 <= or_ln734_6_fu_745_p2;
        or_ln734_7_reg_1454 <= or_ln734_7_fu_750_p2;
        or_ln734_reg_1426 <= or_ln734_fu_715_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln715_reg_1418 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1))) begin
        tmp_V_1_fu_304 <= bytes_plane0_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln717_reg_1422 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1))) begin
        tmp_V_fu_300 <= bytes_plane0_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln708_reg_1409 == 1'd1))) begin
        tmp_val_0_V_1_reg_1458 <= {{bytes_plane0_V_V_dout[55:48]}};
        tmp_val_0_V_2_reg_1488 <= {{bytes_plane0_V_V_dout[103:96]}};
        tmp_val_1_V_1_reg_1463 <= {{bytes_plane0_V_V_dout[63:56]}};
        tmp_val_1_V_2_reg_1493 <= {{bytes_plane0_V_V_dout[111:104]}};
        tmp_val_2_V_1_reg_1468 <= {{bytes_plane0_V_V_dout[71:64]}};
        tmp_val_2_V_2_reg_1498 <= {{bytes_plane0_V_V_dout[119:112]}};
        tmp_val_3_V_1_reg_1473 <= {{bytes_plane0_V_V_dout[79:72]}};
        tmp_val_3_V_2_reg_1503 <= {{bytes_plane0_V_V_dout[127:120]}};
        tmp_val_4_V_1_reg_1478 <= {{bytes_plane0_V_V_dout[87:80]}};
        tmp_val_5_V_1_reg_1483 <= {{bytes_plane0_V_V_dout[95:88]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        trunc_ln1_reg_1343 <= {{mul_ln693_reg_1338[26:15]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (mul_ln131_loc_empty_n == 1'b0) | (real_start == 1'b0)) & (icmp_ln651_fu_486_p2 == 1'd0) & (icmp_ln614_fu_480_p2 == 1'd0) & (icmp_ln571_fu_474_p2 == 1'd0) & (icmp_ln514_fu_452_p2 == 1'd0) & (icmp_ln459_fu_430_p2 == 1'd0) & (icmp_ln418_fu_408_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln688_fu_508_p2 == 1'd1))) begin
        trunc_ln_reg_1316 <= {{add_ln692_fu_518_p2[16:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        x_reg_1413 <= x_fu_689_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln651_fu_486_p2 == 1'd0) & (icmp_ln614_fu_480_p2 == 1'd0) & (icmp_ln571_fu_474_p2 == 1'd0) & (icmp_ln514_fu_452_p2 == 1'd0) & (icmp_ln459_fu_430_p2 == 1'd0) & (icmp_ln418_fu_408_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln688_fu_508_p2 == 1'd1))) begin
        y_reg_1404 <= y_fu_674_p2;
    end
end

always @ (*) begin
    if ((icmp_ln708_fu_684_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state20 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state20 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & ((icmp_ln418_fu_408_p2 == 1'd1) | ((icmp_ln459_fu_430_p2 == 1'd1) | ((icmp_ln514_fu_452_p2 == 1'd1) | ((icmp_ln571_fu_474_p2 == 1'd1) | ((icmp_ln614_fu_480_p2 == 1'd1) | ((icmp_ln651_fu_486_p2 == 1'd1) | ((icmp_ln688_fu_508_p2 == 1'd0) | (icmp_ln700_fu_669_p2 == 1'd1)))))))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln708_reg_1409 == 1'd1))) begin
        ap_phi_mux_x_0_i_i_phi_fu_375_p4 = x_reg_1413;
    end else begin
        ap_phi_mux_x_0_i_i_phi_fu_375_p4 = x_0_i_i_reg_371;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (or_ln717_reg_1422 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (or_ln715_reg_1418 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln708_reg_1409 == 1'd1) & (1'b0 == ap_block_pp0_stage1)))) begin
        bytes_plane0_V_V_blk_n = bytes_plane0_V_V_empty_n;
    end else begin
        bytes_plane0_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op185_read_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op180_read_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln708_reg_1409 == 1'd1)))) begin
        bytes_plane0_V_V_read = 1'b1;
    end else begin
        bytes_plane0_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_559_ap_start = 1'b1;
    end else begin
        grp_fu_559_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1)) | ((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln734_6_reg_1450 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (or_ln734_5_reg_1446 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (or_ln734_4_reg_1442 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (or_ln734_3_reg_1438 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (or_ln734_2_reg_1434 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (or_ln734_1_reg_1430 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln734_reg_1426 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1) & (1'b0 == ap_block_pp0_stage1)))) begin
        img_V_val_0_V_blk_n = img_V_val_0_V_full_n;
    end else begin
        img_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1))) begin
        img_V_val_0_V_din = {{tmp_V_fu_300[87:80]}};
    end else if (((1'b0 == ap_block_pp0_stage7_01001) & (ap_predicate_op228_write_state27 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_0_V_din = {{tmp_V_fu_300[39:32]}};
    end else if (((1'b0 == ap_block_pp0_stage6_01001) & (ap_predicate_op219_write_state26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_0_V_din = {{tmp_V_1_fu_304[119:112]}};
    end else if (((1'b0 == ap_block_pp0_stage5_01001) & (ap_predicate_op209_write_state25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_0_V_din = {{tmp_V_1_fu_304[71:64]}};
    end else if (((1'b0 == ap_block_pp0_stage4_01001) & (ap_predicate_op200_write_state24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_0_V_din = {{tmp_V_1_fu_304[23:16]}};
    end else if (((1'b0 == ap_block_pp0_stage3_01001) & (ap_predicate_op191_write_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_0_V_din = tmp_val_0_V_2_reg_1488;
    end else if (((1'b0 == ap_block_pp0_stage2_01001) & (ap_predicate_op183_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_0_V_din = tmp_val_0_V_1_reg_1458;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_predicate_op166_write_state21 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_V_val_0_V_din = tmp_val_0_V_fu_755_p1;
    end else begin
        img_V_val_0_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_predicate_op228_write_state27 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_predicate_op219_write_state26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op209_write_state25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op200_write_state24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op191_write_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op183_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_predicate_op166_write_state21 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_V_val_0_V_write = 1'b1;
    end else begin
        img_V_val_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1)) | ((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln734_6_reg_1450 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (or_ln734_5_reg_1446 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (or_ln734_4_reg_1442 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (or_ln734_3_reg_1438 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (or_ln734_2_reg_1434 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (or_ln734_1_reg_1430 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln734_reg_1426 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1) & (1'b0 == ap_block_pp0_stage1)))) begin
        img_V_val_1_V_blk_n = img_V_val_1_V_full_n;
    end else begin
        img_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1))) begin
        img_V_val_1_V_din = {{tmp_V_fu_300[95:88]}};
    end else if (((1'b0 == ap_block_pp0_stage7_01001) & (ap_predicate_op228_write_state27 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_1_V_din = {{tmp_V_fu_300[47:40]}};
    end else if (((1'b0 == ap_block_pp0_stage6_01001) & (ap_predicate_op219_write_state26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_1_V_din = {{tmp_V_1_fu_304[127:120]}};
    end else if (((1'b0 == ap_block_pp0_stage5_01001) & (ap_predicate_op209_write_state25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_1_V_din = {{tmp_V_1_fu_304[79:72]}};
    end else if (((1'b0 == ap_block_pp0_stage4_01001) & (ap_predicate_op200_write_state24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_1_V_din = {{tmp_V_1_fu_304[31:24]}};
    end else if (((1'b0 == ap_block_pp0_stage3_01001) & (ap_predicate_op191_write_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_1_V_din = tmp_val_1_V_2_reg_1493;
    end else if (((1'b0 == ap_block_pp0_stage2_01001) & (ap_predicate_op183_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_1_V_din = tmp_val_1_V_1_reg_1463;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_predicate_op166_write_state21 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_V_val_1_V_din = {{bytes_plane0_V_V_dout[15:8]}};
    end else begin
        img_V_val_1_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_predicate_op228_write_state27 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_predicate_op219_write_state26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op209_write_state25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op200_write_state24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op191_write_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op183_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_predicate_op166_write_state21 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_V_val_1_V_write = 1'b1;
    end else begin
        img_V_val_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1)) | ((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln734_6_reg_1450 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (or_ln734_5_reg_1446 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (or_ln734_4_reg_1442 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (or_ln734_3_reg_1438 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (or_ln734_2_reg_1434 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (or_ln734_1_reg_1430 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln734_reg_1426 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1) & (1'b0 == ap_block_pp0_stage1)))) begin
        img_V_val_2_V_blk_n = img_V_val_2_V_full_n;
    end else begin
        img_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1))) begin
        img_V_val_2_V_din = {{tmp_V_fu_300[103:96]}};
    end else if (((1'b0 == ap_block_pp0_stage7_01001) & (ap_predicate_op228_write_state27 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_2_V_din = {{tmp_V_fu_300[55:48]}};
    end else if (((1'b0 == ap_block_pp0_stage6_01001) & (ap_predicate_op219_write_state26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_2_V_din = tmp_val_2_V_5_fu_1095_p1;
    end else if (((1'b0 == ap_block_pp0_stage5_01001) & (ap_predicate_op209_write_state25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_2_V_din = {{tmp_V_1_fu_304[87:80]}};
    end else if (((1'b0 == ap_block_pp0_stage4_01001) & (ap_predicate_op200_write_state24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_2_V_din = {{tmp_V_1_fu_304[39:32]}};
    end else if (((1'b0 == ap_block_pp0_stage3_01001) & (ap_predicate_op191_write_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_2_V_din = tmp_val_2_V_2_reg_1498;
    end else if (((1'b0 == ap_block_pp0_stage2_01001) & (ap_predicate_op183_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_2_V_din = tmp_val_2_V_1_reg_1468;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_predicate_op166_write_state21 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_V_val_2_V_din = {{bytes_plane0_V_V_dout[23:16]}};
    end else begin
        img_V_val_2_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_predicate_op228_write_state27 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_predicate_op219_write_state26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op209_write_state25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op200_write_state24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op191_write_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op183_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_predicate_op166_write_state21 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_V_val_2_V_write = 1'b1;
    end else begin
        img_V_val_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1)) | ((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln734_6_reg_1450 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (or_ln734_5_reg_1446 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (or_ln734_4_reg_1442 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (or_ln734_3_reg_1438 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (or_ln734_2_reg_1434 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (or_ln734_1_reg_1430 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln734_reg_1426 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1) & (1'b0 == ap_block_pp0_stage1)))) begin
        img_V_val_3_V_blk_n = img_V_val_3_V_full_n;
    end else begin
        img_V_val_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1))) begin
        img_V_val_3_V_din = {{tmp_V_fu_300[111:104]}};
    end else if (((1'b0 == ap_block_pp0_stage7_01001) & (ap_predicate_op228_write_state27 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_3_V_din = {{tmp_V_fu_300[63:56]}};
    end else if (((1'b0 == ap_block_pp0_stage6_01001) & (ap_predicate_op219_write_state26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_3_V_din = {{tmp_V_fu_300[15:8]}};
    end else if (((1'b0 == ap_block_pp0_stage5_01001) & (ap_predicate_op209_write_state25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_3_V_din = {{tmp_V_1_fu_304[95:88]}};
    end else if (((1'b0 == ap_block_pp0_stage4_01001) & (ap_predicate_op200_write_state24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_3_V_din = {{tmp_V_1_fu_304[47:40]}};
    end else if (((1'b0 == ap_block_pp0_stage3_01001) & (ap_predicate_op191_write_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_3_V_din = tmp_val_3_V_2_reg_1503;
    end else if (((1'b0 == ap_block_pp0_stage2_01001) & (ap_predicate_op183_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_3_V_din = tmp_val_3_V_1_reg_1473;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_predicate_op166_write_state21 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_V_val_3_V_din = {{bytes_plane0_V_V_dout[31:24]}};
    end else begin
        img_V_val_3_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_predicate_op228_write_state27 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_predicate_op219_write_state26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op209_write_state25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op200_write_state24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op191_write_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op183_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_predicate_op166_write_state21 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_V_val_3_V_write = 1'b1;
    end else begin
        img_V_val_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1)) | ((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln734_6_reg_1450 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (or_ln734_5_reg_1446 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (or_ln734_4_reg_1442 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (or_ln734_3_reg_1438 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (or_ln734_2_reg_1434 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (or_ln734_1_reg_1430 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln734_reg_1426 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1) & (1'b0 == ap_block_pp0_stage1)))) begin
        img_V_val_4_V_blk_n = img_V_val_4_V_full_n;
    end else begin
        img_V_val_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1))) begin
        img_V_val_4_V_din = {{tmp_V_fu_300[119:112]}};
    end else if (((1'b0 == ap_block_pp0_stage7_01001) & (ap_predicate_op228_write_state27 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_4_V_din = {{tmp_V_fu_300[71:64]}};
    end else if (((1'b0 == ap_block_pp0_stage6_01001) & (ap_predicate_op219_write_state26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_4_V_din = {{tmp_V_fu_300[23:16]}};
    end else if (((1'b0 == ap_block_pp0_stage5_01001) & (ap_predicate_op209_write_state25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_4_V_din = {{tmp_V_1_fu_304[103:96]}};
    end else if (((1'b0 == ap_block_pp0_stage4_01001) & (ap_predicate_op200_write_state24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_4_V_din = {{tmp_V_1_fu_304[55:48]}};
    end else if (((1'b0 == ap_block_pp0_stage3_01001) & (ap_predicate_op191_write_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_4_V_din = tmp_val_4_V_2_fu_925_p1;
    end else if (((1'b0 == ap_block_pp0_stage2_01001) & (ap_predicate_op183_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_4_V_din = tmp_val_4_V_1_reg_1478;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_predicate_op166_write_state21 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_V_val_4_V_din = {{bytes_plane0_V_V_dout[39:32]}};
    end else begin
        img_V_val_4_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_predicate_op228_write_state27 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_predicate_op219_write_state26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op209_write_state25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op200_write_state24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op191_write_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op183_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_predicate_op166_write_state21 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_V_val_4_V_write = 1'b1;
    end else begin
        img_V_val_4_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1)) | ((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln734_6_reg_1450 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (or_ln734_5_reg_1446 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (or_ln734_4_reg_1442 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (or_ln734_3_reg_1438 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (or_ln734_2_reg_1434 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (or_ln734_1_reg_1430 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln734_reg_1426 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1) & (1'b0 == ap_block_pp0_stage1)))) begin
        img_V_val_5_V_blk_n = img_V_val_5_V_full_n;
    end else begin
        img_V_val_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1))) begin
        img_V_val_5_V_din = {{tmp_V_fu_300[127:120]}};
    end else if (((1'b0 == ap_block_pp0_stage7_01001) & (ap_predicate_op228_write_state27 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_5_V_din = {{tmp_V_fu_300[79:72]}};
    end else if (((1'b0 == ap_block_pp0_stage6_01001) & (ap_predicate_op219_write_state26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_5_V_din = {{tmp_V_fu_300[31:24]}};
    end else if (((1'b0 == ap_block_pp0_stage5_01001) & (ap_predicate_op209_write_state25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_5_V_din = {{tmp_V_1_fu_304[111:104]}};
    end else if (((1'b0 == ap_block_pp0_stage4_01001) & (ap_predicate_op200_write_state24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_5_V_din = {{tmp_V_1_fu_304[63:56]}};
    end else if (((1'b0 == ap_block_pp0_stage3_01001) & (ap_predicate_op191_write_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_5_V_din = {{tmp_V_1_fu_304[15:8]}};
    end else if (((1'b0 == ap_block_pp0_stage2_01001) & (ap_predicate_op183_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        img_V_val_5_V_din = tmp_val_5_V_1_reg_1483;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_predicate_op166_write_state21 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_V_val_5_V_din = {{bytes_plane0_V_V_dout[47:40]}};
    end else begin
        img_V_val_5_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln734_7_reg_1454 == 1'd1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_predicate_op228_write_state27 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_predicate_op219_write_state26 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op209_write_state25 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op200_write_state24 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op191_write_state23 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op183_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_predicate_op166_write_state21 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_V_val_5_V_write = 1'b1;
    end else begin
        img_V_val_5_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & ((icmp_ln418_fu_408_p2 == 1'd1) | ((icmp_ln459_fu_430_p2 == 1'd1) | ((icmp_ln514_fu_452_p2 == 1'd1) | ((icmp_ln571_fu_474_p2 == 1'd1) | ((icmp_ln614_fu_480_p2 == 1'd1) | ((icmp_ln651_fu_486_p2 == 1'd1) | ((icmp_ln688_fu_508_p2 == 1'd0) | (icmp_ln700_fu_669_p2 == 1'd1)))))))))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        mul_ln131_loc_blk_n = mul_ln131_loc_empty_n;
    end else begin
        mul_ln131_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (mul_ln131_loc_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        mul_ln131_loc_read = 1'b1;
    end else begin
        mul_ln131_loc_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (mul_ln131_loc_empty_n == 1'b0) | (real_start == 1'b0)) & (icmp_ln651_fu_486_p2 == 1'd0) & (icmp_ln614_fu_480_p2 == 1'd0) & (icmp_ln571_fu_474_p2 == 1'd0) & (icmp_ln514_fu_452_p2 == 1'd0) & (icmp_ln459_fu_430_p2 == 1'd0) & (icmp_ln418_fu_408_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln688_fu_508_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | (mul_ln131_loc_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & ((icmp_ln418_fu_408_p2 == 1'd1) | ((icmp_ln459_fu_430_p2 == 1'd1) | ((icmp_ln514_fu_452_p2 == 1'd1) | ((icmp_ln571_fu_474_p2 == 1'd1) | ((icmp_ln614_fu_480_p2 == 1'd1) | ((icmp_ln688_fu_508_p2 == 1'd0) | (icmp_ln651_fu_486_p2 == 1'd1))))))))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((1'b1 == ap_CS_fsm_state19) & ((icmp_ln418_fu_408_p2 == 1'd1) | ((icmp_ln459_fu_430_p2 == 1'd1) | ((icmp_ln514_fu_452_p2 == 1'd1) | ((icmp_ln571_fu_474_p2 == 1'd1) | ((icmp_ln614_fu_480_p2 == 1'd1) | ((icmp_ln651_fu_486_p2 == 1'd1) | ((icmp_ln688_fu_508_p2 == 1'd0) | (icmp_ln700_fu_669_p2 == 1'd1)))))))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln708_fu_684_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln708_fu_684_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln418_fu_392_p2 = ($signed(8'd238) + $signed(trunc_ln133_fu_388_p1));

assign add_ln459_fu_414_p2 = ($signed(trunc_ln133_fu_388_p1) + $signed(8'd234));

assign add_ln514_fu_436_p2 = ($signed(trunc_ln133_fu_388_p1) + $signed(8'd224));

assign add_ln571_fu_458_p2 = ($signed(trunc_ln133_fu_388_p1) + $signed(8'd219));

assign add_ln688_fu_492_p2 = ($signed(trunc_ln133_fu_388_p1) + $signed(8'd236));

assign add_ln692_fu_518_p2 = (17'd15 + zext_ln692_fu_514_p1);

assign add_ln693_fu_554_p2 = (13'd2 + trunc_ln_reg_1316);

assign add_ln715_fu_590_p2 = ($signed(12'd4095) + $signed(trunc_ln1_reg_1343));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((io_acc_block_signal_op237 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln734_7_reg_1454 == 1'd1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((io_acc_block_signal_op237 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln734_7_reg_1454 == 1'd1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((io_acc_block_signal_op237 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln734_7_reg_1454 == 1'd1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op166_write_state21 == 1'b1) & (io_acc_block_signal_op166 == 1'b0)) | ((bytes_plane0_V_V_empty_n == 1'b0) & (icmp_ln708_reg_1409 == 1'd1))));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op166_write_state21 == 1'b1) & (io_acc_block_signal_op166 == 1'b0)) | ((bytes_plane0_V_V_empty_n == 1'b0) & (icmp_ln708_reg_1409 == 1'd1))));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op166_write_state21 == 1'b1) & (io_acc_block_signal_op166 == 1'b0)) | ((bytes_plane0_V_V_empty_n == 1'b0) & (icmp_ln708_reg_1409 == 1'd1))));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op183_write_state22 == 1'b1) & (io_acc_block_signal_op183 == 1'b0)) | ((ap_predicate_op180_read_state22 == 1'b1) & (bytes_plane0_V_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op183_write_state22 == 1'b1) & (io_acc_block_signal_op183 == 1'b0)) | ((ap_predicate_op180_read_state22 == 1'b1) & (bytes_plane0_V_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op183_write_state22 == 1'b1) & (io_acc_block_signal_op183 == 1'b0)) | ((ap_predicate_op180_read_state22 == 1'b1) & (bytes_plane0_V_V_empty_n == 1'b0))));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op191_write_state23 == 1'b1) & (io_acc_block_signal_op191 == 1'b0)) | ((ap_predicate_op185_read_state23 == 1'b1) & (bytes_plane0_V_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op191_write_state23 == 1'b1) & (io_acc_block_signal_op191 == 1'b0)) | ((ap_predicate_op185_read_state23 == 1'b1) & (bytes_plane0_V_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op191_write_state23 == 1'b1) & (io_acc_block_signal_op191 == 1'b0)) | ((ap_predicate_op185_read_state23 == 1'b1) & (bytes_plane0_V_V_empty_n == 1'b0))));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_01001 = ((ap_predicate_op200_write_state24 == 1'b1) & (io_acc_block_signal_op200 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((ap_predicate_op200_write_state24 == 1'b1) & (io_acc_block_signal_op200 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_predicate_op200_write_state24 == 1'b1) & (io_acc_block_signal_op200 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_01001 = ((ap_predicate_op209_write_state25 == 1'b1) & (io_acc_block_signal_op209 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage5_11001 = ((ap_predicate_op209_write_state25 == 1'b1) & (io_acc_block_signal_op209 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((ap_predicate_op209_write_state25 == 1'b1) & (io_acc_block_signal_op209 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_01001 = ((ap_predicate_op219_write_state26 == 1'b1) & (io_acc_block_signal_op219 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage6_11001 = ((ap_predicate_op219_write_state26 == 1'b1) & (io_acc_block_signal_op219 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((ap_predicate_op219_write_state26 == 1'b1) & (io_acc_block_signal_op219 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_01001 = ((ap_predicate_op228_write_state27 == 1'b1) & (io_acc_block_signal_op228 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage7_11001 = ((ap_predicate_op228_write_state27 == 1'b1) & (io_acc_block_signal_op228 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((ap_predicate_op228_write_state27 == 1'b1) & (io_acc_block_signal_op228 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (mul_ln131_loc_empty_n == 1'b0) | (real_start == 1'b0));
end

assign ap_block_state20_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state21_pp0_stage1_iter0 = (((ap_predicate_op166_write_state21 == 1'b1) & (io_acc_block_signal_op166 == 1'b0)) | ((bytes_plane0_V_V_empty_n == 1'b0) & (icmp_ln708_reg_1409 == 1'd1)));
end

always @ (*) begin
    ap_block_state22_pp0_stage2_iter0 = (((ap_predicate_op183_write_state22 == 1'b1) & (io_acc_block_signal_op183 == 1'b0)) | ((ap_predicate_op180_read_state22 == 1'b1) & (bytes_plane0_V_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state23_pp0_stage3_iter0 = (((ap_predicate_op191_write_state23 == 1'b1) & (io_acc_block_signal_op191 == 1'b0)) | ((ap_predicate_op185_read_state23 == 1'b1) & (bytes_plane0_V_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state24_pp0_stage4_iter0 = ((ap_predicate_op200_write_state24 == 1'b1) & (io_acc_block_signal_op200 == 1'b0));
end

always @ (*) begin
    ap_block_state25_pp0_stage5_iter0 = ((ap_predicate_op209_write_state25 == 1'b1) & (io_acc_block_signal_op209 == 1'b0));
end

always @ (*) begin
    ap_block_state26_pp0_stage6_iter0 = ((ap_predicate_op219_write_state26 == 1'b1) & (io_acc_block_signal_op219 == 1'b0));
end

always @ (*) begin
    ap_block_state27_pp0_stage7_iter0 = ((ap_predicate_op228_write_state27 == 1'b1) & (io_acc_block_signal_op228 == 1'b0));
end

always @ (*) begin
    ap_block_state28_pp0_stage0_iter1 = ((io_acc_block_signal_op237 == 1'b0) & (or_ln734_7_reg_1454 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op166_write_state21 = ((or_ln734_reg_1426 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1));
end

always @ (*) begin
    ap_predicate_op180_read_state22 = ((or_ln715_reg_1418 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1));
end

always @ (*) begin
    ap_predicate_op183_write_state22 = ((or_ln734_1_reg_1430 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1));
end

always @ (*) begin
    ap_predicate_op185_read_state23 = ((or_ln717_reg_1422 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1));
end

always @ (*) begin
    ap_predicate_op191_write_state23 = ((or_ln734_2_reg_1434 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1));
end

always @ (*) begin
    ap_predicate_op200_write_state24 = ((or_ln734_3_reg_1438 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1));
end

always @ (*) begin
    ap_predicate_op209_write_state25 = ((or_ln734_4_reg_1442 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1));
end

always @ (*) begin
    ap_predicate_op219_write_state26 = ((or_ln734_5_reg_1446 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1));
end

always @ (*) begin
    ap_predicate_op228_write_state27 = ((or_ln734_6_reg_1450 == 1'd1) & (icmp_ln708_reg_1409 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign grp_fu_559_p1 = 13'd3;

assign icmp_ln418_fu_408_p2 = ((tmp_fu_398_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln459_fu_430_p2 = ((tmp_1_fu_420_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln514_fu_452_p2 = ((tmp_2_fu_442_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln571_fu_474_p2 = ((tmp_3_fu_464_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln614_fu_480_p2 = ((trunc_ln133_fu_388_p1 == 8'd12) ? 1'b1 : 1'b0);

assign icmp_ln651_fu_486_p2 = ((trunc_ln133_fu_388_p1 == 8'd28) ? 1'b1 : 1'b0);

assign icmp_ln688_fu_508_p2 = ((tmp_4_fu_498_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln697_fu_538_p2 = ((remainPix_fu_534_p1 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln700_fu_669_p2 = ((y_0_i_i_reg_360 == Height) ? 1'b1 : 1'b0);

assign icmp_ln708_fu_684_p2 = (($signed(zext_ln708_fu_680_p1) < $signed(trunc_ln1_reg_1343)) ? 1'b1 : 1'b0);

assign icmp_ln715_1_fu_695_p2 = (($signed(zext_ln708_fu_680_p1) < $signed(add_ln715_reg_1349)) ? 1'b1 : 1'b0);

assign icmp_ln715_fu_595_p2 = ((trunc_ln694_fu_576_p1 != 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln717_1_fu_705_p2 = (($signed(zext_ln708_fu_680_p1) < $signed(add_ln715_reg_1349)) ? 1'b1 : 1'b0);

assign icmp_ln717_fu_601_p2 = ((trunc_ln694_fu_576_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln734_1_fu_623_p2 = ((tmp_5_fu_613_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln734_2_fu_629_p2 = ((select_ln697_fu_583_p3 > 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln734_3_fu_645_p2 = ((tmp_6_fu_635_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln734_4_fu_651_p2 = ((select_ln697_fu_583_p3 > 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln734_5_fu_657_p2 = ((select_ln697_fu_583_p3 > 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln734_6_fu_663_p2 = ((select_ln697_fu_583_p3 > 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln734_fu_607_p2 = ((select_ln697_fu_583_p3 != 4'd0) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op166 = (img_V_val_5_V_full_n & img_V_val_4_V_full_n & img_V_val_3_V_full_n & img_V_val_2_V_full_n & img_V_val_1_V_full_n & img_V_val_0_V_full_n);

assign io_acc_block_signal_op183 = (img_V_val_5_V_full_n & img_V_val_4_V_full_n & img_V_val_3_V_full_n & img_V_val_2_V_full_n & img_V_val_1_V_full_n & img_V_val_0_V_full_n);

assign io_acc_block_signal_op191 = (img_V_val_5_V_full_n & img_V_val_4_V_full_n & img_V_val_3_V_full_n & img_V_val_2_V_full_n & img_V_val_1_V_full_n & img_V_val_0_V_full_n);

assign io_acc_block_signal_op200 = (img_V_val_5_V_full_n & img_V_val_4_V_full_n & img_V_val_3_V_full_n & img_V_val_2_V_full_n & img_V_val_1_V_full_n & img_V_val_0_V_full_n);

assign io_acc_block_signal_op209 = (img_V_val_5_V_full_n & img_V_val_4_V_full_n & img_V_val_3_V_full_n & img_V_val_2_V_full_n & img_V_val_1_V_full_n & img_V_val_0_V_full_n);

assign io_acc_block_signal_op219 = (img_V_val_5_V_full_n & img_V_val_4_V_full_n & img_V_val_3_V_full_n & img_V_val_2_V_full_n & img_V_val_1_V_full_n & img_V_val_0_V_full_n);

assign io_acc_block_signal_op228 = (img_V_val_5_V_full_n & img_V_val_4_V_full_n & img_V_val_3_V_full_n & img_V_val_2_V_full_n & img_V_val_1_V_full_n & img_V_val_0_V_full_n);

assign io_acc_block_signal_op237 = (img_V_val_5_V_full_n & img_V_val_4_V_full_n & img_V_val_3_V_full_n & img_V_val_2_V_full_n & img_V_val_1_V_full_n & img_V_val_0_V_full_n);

assign lshr_ln_fu_544_p4 = {{Width[3:1]}};

assign mul_ln693_fu_1265_p0 = 28'd10923;

assign mul_ln693_fu_1265_p1 = mul_ln693_fu_1265_p10;

assign mul_ln693_fu_1265_p10 = add_ln693_reg_1333;

assign or_ln715_fu_700_p2 = (icmp_ln715_reg_1355 | icmp_ln715_1_fu_695_p2);

assign or_ln717_fu_710_p2 = (icmp_ln717_reg_1360 | icmp_ln717_1_fu_705_p2);

assign or_ln734_1_fu_720_p2 = (icmp_ln734_1_fu_623_p2 | icmp_ln717_1_fu_705_p2);

assign or_ln734_2_fu_725_p2 = (icmp_ln734_2_fu_629_p2 | icmp_ln717_1_fu_705_p2);

assign or_ln734_3_fu_730_p2 = (icmp_ln734_3_fu_645_p2 | icmp_ln717_1_fu_705_p2);

assign or_ln734_4_fu_735_p2 = (icmp_ln734_4_fu_651_p2 | icmp_ln717_1_fu_705_p2);

assign or_ln734_5_fu_740_p2 = (icmp_ln734_5_fu_657_p2 | icmp_ln717_1_fu_705_p2);

assign or_ln734_6_fu_745_p2 = (icmp_ln734_6_fu_663_p2 | icmp_ln717_1_fu_705_p2);

assign or_ln734_7_fu_750_p2 = (icmp_ln717_1_fu_705_p2 | icmp_ln697_fu_538_p2);

assign or_ln734_fu_715_p2 = (icmp_ln734_fu_607_p2 | icmp_ln717_1_fu_705_p2);

assign remainPix_fu_534_p1 = Width[3:0];

assign select_ln697_fu_583_p3 = ((icmp_ln697_fu_538_p2[0:0] === 1'b1) ? 4'd8 : zext_ln697_fu_580_p1);

assign start_out = real_start;

assign tmp_1_fu_420_p4 = {{add_ln459_fu_414_p2[7:1]}};

assign tmp_2_fu_442_p4 = {{add_ln514_fu_436_p2[7:1]}};

assign tmp_3_fu_464_p4 = {{add_ln571_fu_458_p2[7:1]}};

assign tmp_4_fu_498_p4 = {{add_ln688_fu_492_p2[7:1]}};

assign tmp_5_fu_613_p4 = {{select_ln697_fu_583_p3[3:1]}};

assign tmp_6_fu_635_p4 = {{select_ln697_fu_583_p3[3:2]}};

assign tmp_fu_398_p4 = {{add_ln418_fu_392_p2[7:1]}};

assign tmp_val_0_V_fu_755_p1 = bytes_plane0_V_V_dout[7:0];

assign tmp_val_2_V_5_fu_1095_p1 = tmp_V_fu_300[7:0];

assign tmp_val_4_V_2_fu_925_p1 = tmp_V_1_fu_304[7:0];

assign trunc_ln133_fu_388_p1 = HwReg_video_format[7:0];

assign trunc_ln694_fu_576_p1 = grp_fu_559_p2[1:0];

assign x_fu_689_p2 = (ap_phi_mux_x_0_i_i_phi_fu_375_p4 + 11'd1);

assign y_fu_674_p2 = (y_0_i_i_reg_360 + 16'd1);

assign zext_ln692_fu_514_p1 = mul_ln131_loc_dout;

assign zext_ln697_fu_580_p1 = lshr_ln_fu_544_p4;

assign zext_ln708_fu_680_p1 = ap_phi_mux_x_0_i_i_phi_fu_375_p4;

endmodule //v_frmbuf_rd_0_Bytes2MultiPixStream
